
title: KutologoJM's Portfolio
author: KutologoJM
email: kutologomashego@gmail.com
github:
  is_project_page: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme


exclude:
  - README.md
  - sync.py